/** Shapes of the build-time data in src/data/. Generated by scripts/extract.mjs. */

export type MediaKind = 'youtube' | 'link' | 'flash';

export interface Media {
  kind: MediaKind;
  url: string;
  /** YouTube video id, present when kind === 'youtube'. */
  id?: string;
  note?: string;
}

export interface Post {
  id: number;
  /** ISO local date, e.g. "2010-02-13T21:04:11". */
  date: string;
  title: string;
  slug: string;
  /** Canonical permalink, e.g. "/2010/02/13/tinas-tiny-sizes/". */
  permalink: string;
  /** Sanitized at build time. Safe for dangerouslySetInnerHTML. */
  html: string;
  quote: string | null;
  speaker: string | null;
  speakerRaw: string | null;
  /** Present only when a post has more than one attributed speaker. */
  speakers?: string[];
  context: string | null;
  /** Trailing prose after the quote -- usually a "See <other post>" link. */
  note?: string;
  /** True when no quote could be parsed; `html` is the whole story. */
  unparsed?: boolean;
  categories: string[];
  tags: string[];
  images: string[];
  media?: Media[];
}

export interface Page {
  id: number;
  title: string;
  slug: string;
  date: string;
  permalink: string;
  html: string;
}

export interface Facet {
  name: string;
  slug: string;
  count: number;
}

export interface YearCount {
  year: string;
  count: number;
}

export interface Meta {
  generatedFrom: string;
  postCount: number;
  parseFailures: number;
  definedTagCount: number;
  tags: Facet[];
  categories: Facet[];
  speakers: Facet[];
  years: YearCount[];
}
